In [49]:
import pandas as pd
import numpy as np
import seaborn as sns
import os

In [50]:
os.chdir(r'C:\Users\Shyam Adsul\Python codes SSPU\Data sets')
df  = pd.read_csv('horse.csv')

In [51]:
df.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no

In [52]:
df.isnull().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities       56
peripheral_pulse          69
mucous_membrane           47
capillary_refill_time     32
pain                      55
peristalsis               44
abdominal_distention      56
nasogastric_tube         104
nasogastric_reflux       106
nasogastric_reflux_ph    246
rectal_exam_feces        102
abdomen                  118
packed_cell_volume        29
total_protein             33
abdomo_appearance        165
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

In [53]:
print(df['rectal_temp'].mean())
print(df['rectal_temp'].median())
print(df['rectal_temp'].mode())

38.16861924686195
38.2
0    38.0
dtype: float64

In [54]:
df['rectal_temp'].fillna(df['rectal_temp'].mean(),inplace = True)

In [55]:
df

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.500000,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.200000,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.300000,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.100000,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.300000,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,yes,adult,533886,38.168619,120.0,70.0,cold,NaN,pale_cyanotic,more_3_sec,...,55.0,65.0,NaN,NaN,euthanized,no,3205,0,0,no
295,no,adult,527702,37.200000,72.0,24.0,cool,increased,pale_cyanotic,more_3_sec,...,44.0,NaN,serosanguious,3.3,euthanized,yes,2208,0,0,yes
296,yes,adult,529386,37.500000,72.0,30.0,cold,reduced,pale_cyanotic,less_3_sec,...,60.0,6.8,NaN,NaN,died,yes,3205,0,0,no
297,yes,adult,530612,36.500000,100.0,24.0,cool,reduced,pale_pink,less_3_sec,...,50.0,6.0,serosanguious,3.4,lived,yes,2208,0,0,yes
298,yes,adult,534618,37.200000,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,clear,1.0,euthanized,no,6112,0,0,no

In [56]:
print(df['pulse'].mean())
print(df['pulse'].median())
print(df['pulse'].mode())

72.0
64.0
0    48.0
dtype: float64

In [57]:
df['pulse'].fillna(df['pulse'].mean(),inplace = True)

In [58]:
print(df['respiratory_rate'].mean())
print(df['respiratory_rate'].median())
print(df['respiratory_rate'].mode())

30.46058091286307
25.0
0    20.0
1    24.0
dtype: float64

In [59]:
df['respiratory_rate'].fillna(df['respiratory_rate'].mean(),inplace = True)

In [60]:
df['temp_of_extremities'].fillna(df['temp_of_extremities'].mode()[0],inplace = True)

In [61]:
df['peripheral_pulse'].fillna(df['peripheral_pulse'].mode()[0],inplace = True)

In [62]:
df['mucous_membrane'].fillna(df['mucous_membrane'].mode()[0],inplace = True)

In [63]:
df['capillary_refill_time'].fillna(df['capillary_refill_time'].mode()[0],inplace = True)

In [64]:
df['pain'].fillna(df['pain'].mode()[0],inplace = True)

In [65]:
df['peristalsis'].fillna(df['peristalsis'].mode()[0],inplace = True)

In [66]:
df['abdominal_distention'].fillna(df['abdominal_distention'].mode()[0],inplace = True)

In [67]:
df.isnull().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp                0
pulse                      0
respiratory_rate           0
temp_of_extremities        0
peripheral_pulse           0
mucous_membrane            0
capillary_refill_time      0
pain                       0
peristalsis                0
abdominal_distention       0
nasogastric_tube         104
nasogastric_reflux       106
nasogastric_reflux_ph    246
rectal_exam_feces        102
abdomen                  118
packed_cell_volume        29
total_protein             33
abdomo_appearance        165
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

In [68]:
type(df['nasogastric_tube'])

pandas.core.series.Series

In [69]:
df['nasogastric_tube'].fillna(df['nasogastric_tube'].mode()[0],inplace = True)
df['nasogastric_reflux'].fillna(df['nasogastric_reflux'].mode()[0],inplace = True)
df['nasogastric_reflux_ph'].fillna(df['nasogastric_reflux_ph'].mode()[0],inplace = True)
df['rectal_exam_feces'].fillna(df['rectal_exam_feces'].mode()[0],inplace = True)
df['abdomen'].fillna(df['abdomen'].mode()[0],inplace = True)
df['packed_cell_volume'].fillna(df['packed_cell_volume'].mode()[0],inplace = True)
df['total_protein'].fillna(df['total_protein'].mode()[0],inplace = True)
df['abdomo_appearance'].fillna(df['abdomo_appearance'].mode()[0],inplace = True)
df['abdomo_protein'].fillna(df['abdomo_protein'].mode()[0],inplace = True)

In [70]:
# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 

df['outcome']= label_encoder.fit_transform(df['outcome']) 

#df['outcome'] = number.fit_transform(df['outcome'].astype('int'))

In [71]:
df['outcome'].unique

<bound method Series.unique of 0      0
1      1
2      2
3      0
4      0
      ..
294    1
295    1
296    0
297    2
298    1
Name: outcome, Length: 299, dtype: int32>

In [72]:
df.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,normal_pink,more_3_sec,...,45.0,8.4,cloudy,2.0,0,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,cool,normal,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,1,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,cloudy,2.0,2,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,0,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,cool,normal,dark_cyanotic,more_3_sec,...,74.0,7.4,cloudy,2.0,0,no,4300,0,0,no

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                299 non-null    object
 1   age                    299 non-null    object
 2   hospital_number        299 non-null    int64
 3   rectal_temp            299 non-null    float64
 4   pulse                  299 non-null    float64
 5   respiratory_rate       299 non-null    float64
 6   temp_of_extremities    299 non-null    object
 7   peripheral_pulse       299 non-null    object
 8   mucous_membrane        299 non-null    object
 9   capillary_refill_time  299 non-null    object
 10  pain                   299 non-null    object
 11  peristalsis            299 non-null    object
 12  abdominal_distention   299 non-null    object
 13  nasogastric_tube       299 non-null    object
 14  nasogastric_reflux     299 non-null    object
 15  nasogastric_reflux_ph  299 non-null    float64
 16  rectal_exam_feces      299 non-null    object
 17  abdomen                299 non-null    object
 18  packed_cell_volume     299 non-null    float64
 19  total_protein          299 non-null    float64
 20  abdomo_appearance      299 non-null    object
 21  abdomo_protein         299 non-null    float64
 22  outcome                299 non-null    int32
 23  surgical_lesion        299 non-null    object
 24  lesion_1               299 non-null    int64
 25  lesion_2               299 non-null    int64
 26  lesion_3               299 non-null    int64
 27  cp_data                299 non-null    object
dtypes: float64(7), int32(1), int64(4), object(16)
memory usage: 64.4+ KB

In [74]:
df['surgery']= label_encoder.fit_transform(df['surgery']) 
df['age']= label_encoder.fit_transform(df['age']) 
df['temp_of_extremities']= label_encoder.fit_transform(df['temp_of_extremities']) 
df['peripheral_pulse']= label_encoder.fit_transform(df['peripheral_pulse']) 
df['mucous_membrane']= label_encoder.fit_transform(df['mucous_membrane']) 
df['capillary_refill_time']= label_encoder.fit_transform(df['capillary_refill_time']) 
df['peristalsis']= label_encoder.fit_transform(df['peristalsis'])
df['abdominal_distention']= label_encoder.fit_transform(df['abdominal_distention'])
df['nasogastric_tube']= label_encoder.fit_transform(df['nasogastric_tube'])
df['nasogastric_reflux']= label_encoder.fit_transform(df['nasogastric_reflux'])
df['rectal_exam_feces']= label_encoder.fit_transform(df['rectal_exam_feces'])
df['abdomen']= label_encoder.fit_transform(df['abdomen'])
df['abdomo_appearance']= label_encoder.fit_transform(df['abdomo_appearance'])
df['surgical_lesion']= label_encoder.fit_transform(df['surgical_lesion'])
df['cp_data']=label_encoder.fit_transform(df['cp_data'])
df['pain']=label_encoder.fit_transform(df['pain'])

In [75]:
df.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,0,0,530101,38.5,66.0,28.0,1,3,3,2,...,45.0,8.4,1,2.0,0,0,11300,0,0,0
1,1,0,534817,39.2,88.0,20.0,1,2,4,1,...,50.0,85.0,1,2.0,1,0,2208,0,0,0
2,0,0,530334,38.3,40.0,24.0,2,2,5,1,...,33.0,6.7,1,2.0,2,0,0,0,0,1
3,1,1,5290409,39.1,164.0,84.0,0,2,2,2,...,48.0,7.2,2,5.3,0,1,2208,0,0,1
4,0,0,530255,37.3,104.0,35.0,1,2,2,2,...,74.0,7.4,1,2.0,0,0,4300,0,0,0

In [76]:
df.isnull().sum()

surgery                  0
age                      0
hospital_number          0
rectal_temp              0
pulse                    0
respiratory_rate         0
temp_of_extremities      0
peripheral_pulse         0
mucous_membrane          0
capillary_refill_time    0
pain                     0
peristalsis              0
abdominal_distention     0
nasogastric_tube         0
nasogastric_reflux       0
nasogastric_reflux_ph    0
rectal_exam_feces        0
abdomen                  0
packed_cell_volume       0
total_protein            0
abdomo_appearance        0
abdomo_protein           0
outcome                  0
surgical_lesion          0
lesion_1                 0
lesion_2                 0
lesion_3                 0
cp_data                  0
dtype: int64

In [77]:
df.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,0,0,530101,38.5,66.0,28.0,1,3,3,2,...,45.0,8.4,1,2.0,0,0,11300,0,0,0
1,1,0,534817,39.2,88.0,20.0,1,2,4,1,...,50.0,85.0,1,2.0,1,0,2208,0,0,0
2,0,0,530334,38.3,40.0,24.0,2,2,5,1,...,33.0,6.7,1,2.0,2,0,0,0,0,1
3,1,1,5290409,39.1,164.0,84.0,0,2,2,2,...,48.0,7.2,2,5.3,0,1,2208,0,0,1
4,0,0,530255,37.3,104.0,35.0,1,2,2,2,...,74.0,7.4,1,2.0,0,0,4300,0,0,0

In [78]:
df.columns

Index(['surgery', 'age', 'hospital_number', 'rectal_temp', 'pulse',
       'respiratory_rate', 'temp_of_extremities', 'peripheral_pulse',
       'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis',
       'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux',
       'nasogastric_reflux_ph', 'rectal_exam_feces', 'abdomen',
       'packed_cell_volume', 'total_protein', 'abdomo_appearance',
       'abdomo_protein', 'outcome', 'surgical_lesion', 'lesion_1', 'lesion_2',
       'lesion_3', 'cp_data'],
      dtype='object')

In [79]:
df1 = df[['hospital_number', 'rectal_temp', 'pulse',
       'respiratory_rate',
       'nasogastric_reflux_ph',
       'packed_cell_volume', 'total_protein',
       'abdomo_protein', 'lesion_1', 'lesion_2',
       'lesion_3']]

In [80]:
df1.head()

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,lesion_3
0,530101,38.5,66.0,28.0,2.0,45.0,8.4,2.0,11300,0,0
1,534817,39.2,88.0,20.0,2.0,50.0,85.0,2.0,2208,0,0
2,530334,38.3,40.0,24.0,2.0,33.0,6.7,2.0,0,0,0
3,5290409,39.1,164.0,84.0,5.0,48.0,7.2,5.3,2208,0,0
4,530255,37.3,104.0,35.0,2.0,74.0,7.4,2.0,4300,0,0

In [81]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
new_data=scaler.fit_transform(df1)

In [82]:
df1 = pd.DataFrame(new_data, columns = [['hospital_number','rectal_temp','pulse','respiratory_rate','nasogastric_reflux_ph','packed_cell_volume','total_protein','abdomo_protein','lesion_1','lesion_2','lesion_3']])

In [83]:
df1

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,lesion_3
0,-0.364592,5.062087e-01,-0.218798,-0.155463,-0.362536,-0.039384,-0.527864,-0.283256,1.415021,-0.139371,-0.057928
1,-0.361509,1.575511e+00,0.583463,-0.660914,-0.362536,0.447216,2.378426,-0.283256,-0.268864,-0.139371,-0.057928
2,-0.364440,2.006938e-01,-1.166925,-0.408189,-0.362536,-1.207222,-0.592364,-0.283256,-0.677797,-0.139371,-0.057928
3,2.747804,1.422753e+00,3.354910,3.382695,1.903628,0.252576,-0.573393,2.378542,-0.268864,-0.139371,-0.057928
4,-0.364491,-1.326880e+00,1.166925,0.286807,-0.362536,2.782893,-0.565805,-0.283256,0.118585,-0.139371,-0.057928
...,...,...,...,...,...,...,...,...,...,...,...
294,-0.362117,2.170813e-14,1.750388,2.498156,-0.362536,0.933815,1.619604,-0.283256,-0.084214,-0.139371,-0.057928
295,-0.366161,-1.479638e+00,0.000000,-0.408189,-0.362536,-0.136703,-0.599952,0.765331,-0.268864,-0.139371,-0.057928
296,-0.365060,-1.021366e+00,0.000000,-0.029100,-0.362536,1.420414,-0.588570,-0.283256,-0.084214,-0.139371,-0.057928
297,-0.364258,-2.548940e+00,1.021059,-0.408189,-0.362536,0.447216,-0.618923,0.845991,-0.268864,-0.139371,-0.057928
298,-0.361639,-1.479638e+00,-1.166925,-0.660914,-0.362536,-0.915262,1.505781,-1.089861,0.454177,-0.139371,-0.057928

In [84]:
df2 = df.drop(['hospital_number','rectal_temp','pulse','respiratory_rate','nasogastric_reflux_ph','packed_cell_volume','total_protein','abdomo_protein','lesion_1','lesion_2','lesion_3'],axis = 1)

In [85]:
df2

,surgery,age,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,pain,peristalsis,abdominal_distention,nasogastric_tube,nasogastric_reflux,rectal_exam_feces,abdomen,abdomo_appearance,outcome,surgical_lesion,cp_data
0,0,0,1,3,3,2,2,0,2,2,2,1,0,1,0,0,0
1,1,0,1,2,4,1,3,0,3,2,2,0,4,1,1,0,0
2,0,0,2,2,5,1,3,2,1,2,2,3,3,1,2,0,1
3,1,1,0,2,2,2,1,0,2,0,0,1,0,2,0,1,1
4,0,0,1,2,2,2,3,2,1,2,2,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,1,0,0,2,4,2,1,0,1,2,2,0,0,1,1,0,0
295,0,0,1,1,4,2,4,2,0,1,2,0,1,2,1,1,1
296,1,0,0,3,4,1,4,0,0,2,2,1,0,1,0,1,0
297,1,0,1,3,5,1,3,2,0,1,2,0,1,2,2,1,1
298,1,0,1,2,3,1,3,2,1,2,2,0,3,0,1,0,0

In [86]:
df3 = pd.concat([df1,df2],axis = 1)

In [87]:
df3.head()

,"(hospital_number,)","(rectal_temp,)","(pulse,)","(respiratory_rate,)","(nasogastric_reflux_ph,)","(packed_cell_volume,)","(total_protein,)","(abdomo_protein,)","(lesion_1,)","(lesion_2,)",...,peristalsis,abdominal_distention,nasogastric_tube,nasogastric_reflux,rectal_exam_feces,abdomen,abdomo_appearance,outcome,surgical_lesion,cp_data
0,-0.364592,0.506209,-0.218798,-0.155463,-0.362536,-0.039384,-0.527864,-0.283256,1.415021,-0.139371,...,0,2,2,2,1,0,1,0,0,0
1,-0.361509,1.575511,0.583463,-0.660914,-0.362536,0.447216,2.378426,-0.283256,-0.268864,-0.139371,...,0,3,2,2,0,4,1,1,0,0
2,-0.364440,0.200694,-1.166925,-0.408189,-0.362536,-1.207222,-0.592364,-0.283256,-0.677797,-0.139371,...,2,1,2,2,3,3,1,2,0,1
3,2.747804,1.422753,3.354910,3.382695,1.903628,0.252576,-0.573393,2.378542,-0.268864,-0.139371,...,0,2,0,0,1,0,2,0,1,1
4,-0.364491,-1.326880,1.166925,0.286807,-0.362536,2.782893,-0.565805,-0.283256,0.118585,-0.139371,...,2,1,2,2,0,0,1,0,0,0

In [88]:
x = df3.drop('outcome',axis = 1)

In [89]:
y = df3['outcome']

In [116]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.32)

In [117]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [118]:
y_pred = gnb.predict(x_test)
print('Accuracy {:.2f}'.format(gnb.score(x_test, y_test)))

Accuracy 0.52